development:
  adapter: mysql2
  host: localhost
  database: rails_mall_dev
  username: root
  password:
  pool: 5
  timeout: 5000
test:
  adapter: mysql2
  host: localhost
  database: rails_mall_test
  username: root
  password:
  pool: 5
  timeout: 5000
production:
  adapter: mysql2
  host: localhost
  database: rails_mall_pro
  username: root
  password:
  pool: 5
  timeout: 5000
